Add checks for release and debug binaries in GitHub Actions workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -38,6 +38,19 @@ jobs:
           make linux-release
           make linux-debug
 
+      - name: Check if files exist
+        run: |
+          if [ ! -f "./bin/Nebulite" ]; then
+            echo "Release binary not found!"
+            tree .
+            exit 1
+          fi
+          if [ ! -f "./bin/Nebulite_Debug" ]; then
+            echo "Debug binary not found!"
+            tree .
+            exit 1
+          fi
+
       - name: Run tests
         run: |
           make test
